### ISSUE TITLE
Erro: list index out of range.

### ISSUE THREAD

**Issue by DevLucasFontoura** [DevLucasFontoura/Deletar_Arquivos#5]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Administrador\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Administrador\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 861, in callit
    func(*args)
  File "c:\Users\Administrador\Desktop\Deletar_Arquivos\script\script.py", line 152, in <lambda>
    showAnimation = splash.after(50, lambda: animation(count, imgObject, gif, splash))
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Administrador\Desktop\Deletar_Arquivos\script\script.py", line 146, in animation
    newImage = imgObject[count]
               ~~~~~~~~~^^^^^^^
IndexError: list index out of range

**Comment by DevLucasFontoura** [comment]
Resolvido.

**Comment by DevLucasFontoura** [comment]
Resolvido.
